### PR TITLE
fix: wildcard event is not handled correctly

### PR DESCRIPTION
**Pull request by orenwang**
Related: https://github.com/supabase-community/realtime-py/issues/32

### CODE REVIEW

**Review by odiseo0 — CHANGES_REQUESTED** [review]
I would go with

```py
if cl.event == "*" or cl.event == msg.event:
   cl.callback(msg.payload)
```

**Comment by orenwang** [comment]
@odiseo0 Yeah... I figure the team has given up on the client for python.

**Comment by dreinon** [comment]
Hi! We haven't given up, it is just that we have prioritized postgrest, storage and gotrue since these are the most used clients, but we do want to pay attention to the realtime client as well. We'll try to be more active in this repo 🙂

**Comment by orenwang** [comment]
@dreinon That sounds great. And of course it makes sense to prioritize other repos!

**Pull request merged**
