### PR TITLE
Update websockets + pytest versions

### PR DESCRIPTION
**Pull request by markyao6275**
## What kind of change does this PR introduce?

Dependency version update

## What is the current behavior?

https://github.com/supabase-community/realtime-py/issues/61

## What is the new behavior?

Updated websockets + pytest version

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by markyao6275** [comment]
@anand2312 could I get a review on this. Would be nice to upgrade to the latest version of `websockets`.

**Review by anand2312 — APPROVED** [review]
(sorry it took a while)

**Comment by markyao6275** [comment]
@anand2312 Thanks! Anything else required before merging? I don't see a merge button on my end, so could you merge this PR?

**Comment by anand2312** [comment]
Thanks for the PR @markyao6275

**Pull request merged**
