### PR TITLE
♻️ Standardize types and improve consistency

### PR DESCRIPTION
**Pull request by odiseo0**
The goal of this PR is to make the code more standard and compatible with lower versions of Python as well
Maybe there are some things to consider like:

1. Include `typing-extensions` to the dependencies (If is not in the dependencies)
2. Use the `typing` versions of `list` and `dict` (I changed those in this PR)

### CODE REVIEW

**Review by anand2312 — COMMENTED** [review]
Thanks for the PR!

What's the reasoning behind making typevars/paramspecs in a separate file though? Imo it's a little clearer if they're defined where they're used but that's up to debate 🤔

**Comment by odiseo0** [comment]
That's true, let me change that real quick and sorry for the late response

**Comment by odiseo0** [comment]
I also removed `T` because I wasn't using it anywhere in the code, the thing I dislike is the conditional import, maybe we should use `typing-extensions` directly instead of condition those imports

**Review by anand2312 — APPROVED** [review]
LGTM

**Pull request merged**
